// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MenSneakers struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}

type Mutation struct {
}

type Query struct {
}

type WomenSneakers struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}
